import type { Metadata } from "next";
import { Inter, Poppins,  } from "next/font/google";
import { Montserrat } from 'next/font/google';

import localFont from "next/font/local";
import "./globals.css";
import Footer from "@/components/Footer";
import TopHeader from "@/components/Topheader";
import Header from "@/components/header";

const inter = Inter({ subsets: ["latin"], 
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"] });



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
})

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'], // Adjust as needed
  variable: '--font-clash-display',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={inter.className}
      >
        <TopHeader />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
